version: 2
updates:
- package-ecosystem: github-actions
  directory: /
  schedule:
    interval: daily

- package-ecosystem: terraform
  directories:
  - /modules/account
  - /modules/organization
  - /modules/organizational-unit
  - /modules/ram-share
  - /modules/sso-access-control-attributes
  - /modules/sso-account-assignment
  - /modules/sso-permission-set
  schedule:
    interval: weekly
