# Modules
- color: "fbca04"
  description: "This issue or pull request is related to account module."
  name: ":floppy_disk: account"
- color: "fbca04"
  description: "This issue or pull request is related to organization module."
  name: ":floppy_disk: organization"
- color: "fbca04"
  description: "This issue or pull request is related to organization-policy module."
  name: ":floppy_disk: organization-policy"
- color: "fbca04"
  description: "This issue or pull request is related to organizational-unit module."
  name: ":floppy_disk: organizational-unit"
- color: "fbca04"
  description: "This issue or pull request is related to ram-share module."
  name: ":floppy_disk: ram-share"
- color: "fbca04"
  description: "This issue or pull request is related to sso-access-control-attributes module."
  name: ":floppy_disk: sso-access-control-attributes"
- color: "fbca04"
  description: "This issue or pull request is related to sso-account-assignment module."
  name: ":floppy_disk: sso-account-assignment"
- color: "fbca04"
  description: "This issue or pull request is related to sso-permission-set module."
  name: ":floppy_disk: sso-permission-set"
