# Warning
- color: "ee0701"
  description: "Categorize bug reports."
  name: ":warning: bug"
- color: "ee0701"
  description: "Categorize vulnerability reports."
  name: ":warning: vulnerability"

# Highlight
- color: "0e8a16"
  description: "Good for newcomers."
  name: ":fire: good first issue"
- color: "0e8a16"
  description: "Extra attention is needed."
  name: ":fire: help wanted"

# Cancel
- color: "b60205"
  description: "This issue or pull request already exists."
  name: ":pray: duplicate"
- color: "b60205"
  description: "This will not be worked on."
  name: ":pray: wontfix"

# Size
- color: "cfd3d7"
  description: "Extra Small size issue or PR."
  name: "size/XS"
- color: "cfd3d7"
  description: "Small size issue or PR."
  name: "size/S"
- color: "cfd3d7"
  description: "Medium size issue or PR."
  name: "size/M"
- color: "cfd3d7"
  description: "Large size issue or PR."
  name: "size/L"
- color: "cfd3d7"
  description: "Extra Large size issue or PR."
  name: "size/XL"

# Modules
- color: "fbca04"
  description: "This issue or pull request is related to account module."
  name: ":floppy_disk: account"
- color: "fbca04"
  description: "This issue or pull request is related to organization module."
  name: ":floppy_disk: organization"
- color: "fbca04"
  description: "This issue or pull request is related to organizational-unit module."
  name: ":floppy_disk: organizational-unit"
- color: "fbca04"
  description: "This issue or pull request is related to ram-share module."
  name: ":floppy_disk: ram-share"
- color: "fbca04"
  description: "This issue or pull request is related to sso-access-control-attributes module."
  name: ":floppy_disk: sso-access-control-attributes"
- color: "fbca04"
  description: "This issue or pull request is related to sso-account-assignment module."
  name: ":floppy_disk: sso-account-assignment"
- color: "fbca04"
  description: "This issue or pull request is related to sso-permission-set module."
  name: ":floppy_disk: sso-permission-set"
